UI - view customer page
estagio-2023/realestate-ui pull request #92
Opened 2024-05-20 15:46 UTC by evaalves2042

2024-05-20 15:48 UTC, RafaelMeha commented on src/app/view-customer/view-customer.component.ts
> +//import { Component } from '@angular/core';
Remove comment

2024-05-20 16:15 UTC, Silva096 commented on src/app/customer-management/customer-management.component.spec.ts
> +
remove new line pls

2024-05-20 16:16 UTC, Silva096 commented on src/app/customer-management/customer-management.component.html
> +  <div>
remove extra div :)

2024-05-20 16:16 UTC, Silva096 commented on src/app/customer-management/customer-management.component.html
> +
remove new lines

2024-05-20 16:16 UTC, Silva096 commented on src/app/api.service.ts
> +@Injectable({
Is this needed?

2024-05-20 16:17 UTC, Silva096 commented on src/app/models/view-customer.ts
> +export interface custumerId{
custumer should be customer

2024-05-20 16:18 UTC, Silva096 commented on src/app/view-customer/view-customer.component.html
> +                <img alt="" style="width:500px;border-radius: 50%;" title="" class="img-circle img-thumbnail isTooltip" src="https://bootdey.com/img/Content/avatar/avatar7.png" data-original-title="u
isToolTip is doing anything?

2024-05-20 16:19 UTC, Silva096 commented on src/app/view-customer/view-customer.component.html
> +                <img alt="" style="width:500px;border-radius: 50%;" title="" class="img-circle img-thumbnail isTooltip" src="https://bootdey.com/img/Content/avatar/avatar7.png" data-original-title="u
Is this supposed to exist and in Portuguese? 
data-original-title="utilizador"

2024-05-20 16:19 UTC, Silva096 commented on src/app/view-customer/view-customer.component.ts
> +
extra new line not needed. Leave only 1 please

2024-05-20 16:19 UTC, Silva096 commented on src/app/view-customer/view-customer.component.ts
> +
remove 7 new lines

2024-05-20 16:21 UTC, Silva096 requested changes
home_page_icons -> should be changed to customer_icons

2024-05-24 11:57 UTC, Silva096 approved these changes

2024-05-24 11:57 UTC, merged